import images from "./gallery-images.json";

/**
 * Gallery content. Image files + sizes are generated by
 * `python scripts/build_gallery.py <folder>` into gallery-images.json.
 * Everything a human edits lives here: alt text, captions, order, hiding.
 * Keys are the 10-char file hashes (public/gallery/<key>.webp).
 */

type Meta = { alt: string; caption?: string };

// Shown first, in this order. Everything else follows newest-first.
const pinned = ["96d272bc96", "5d6f1286d7", "4784a03c91", "07f43fa294"];

// Kept on disk but not shown (near-duplicates).
const hidden = new Set(["3959f2848c", "af099ac2c8"]);

const meta: Record<string, Meta> = {
  "96d272bc96": {
    alt: "Team Aloo Siddo on stage with the Hacktropica 2026 first runners-up cheque",
    caption: "Hacktropica 2026, 1st runners-up",
  },
  "5d6f1286d7": {
    alt: "Holding up the Synchronicity S2.0 first runner-up trophy",
    caption: "Synchronicity S2.0, 1st runners-up",
  },
  "34fd7ba370": {
    alt: "Selfie with teammates and the Synchronicity S2.0 trophy",
    caption: "Synchronicity S2.0, Jadavpur University",
  },
  "4784a03c91": {
    alt: "Standing at the MetaMorph hackathon entrance",
    caption: "MetaMorph",
  },
  f6f984201b: {
    alt: "Collage of MetaMorph hackathon moments",
    caption: "MetaMorph",
  },
  "07f43fa294": {
    alt: "Hackolution 2K26 participant badge",
    caption: "Hackolution 2K26",
  },
  "5637bbf2ff": {
    alt: "Standing beside the Hackolution banner",
    caption: "Hackolution 2K26",
  },
  bab2b03094: {
    alt: "At the GeeksforGeeks office in Kolkata",
    caption: "GeeksforGeeks, Kolkata",
  },
  "54c24aba08": { alt: "Team selfie at the venue desks" },
  "1b06f5b259": { alt: "Teammates at the hacking desks" },
  "3475773be7": { alt: "Receiving an award on the hackathon floor" },
  aec0bc19ec: { alt: "Team photo outside the venue" },
  c79f7816cb: { alt: "Group selfie with fellow hackers" },
  f408b3e96a: { alt: "Group selfie with fellow hackers" },
  "43975a88de": { alt: "The hacking floor mid-event" },
  "5d27caa2a0": { alt: "Team selfie at the workstations" },
  ebb43681ac: { alt: "Collage of team photos and hackathon badges" },
  "3f29704e35": { alt: "Collage of the venue, stickers and the team" },
  "4057f3a006": { alt: "Team photo in a lab" },
};

type Generated = {
  src: string;
  width: number;
  height: number;
  blur: string;
  takenAt: string | null;
};

export type GalleryPhoto = Generated & Meta & { key: string };

const all = Object.entries(images as Record<string, Generated>)
  .filter(([key]) => !hidden.has(key))
  .map(([key, img]) => ({
    key,
    ...img,
    ...(meta[key] ?? { alt: "Photo from a hackathon" }),
  }));

const rank = (p: GalleryPhoto) => {
  const i = pinned.indexOf(p.key);
  return i === -1 ? pinned.length : i;
};

export const galleryPhotos: GalleryPhoto[] = all.sort(
  (a, b) =>
    rank(a) - rank(b) || (b.takenAt ?? "").localeCompare(a.takenAt ?? ""),
);
